### ISSUE TITLE
Error in emacs 25

### ISSUE THREAD

**Issue by deerpig** [emacs-helm/helm-dictionary#28]
Calling helm-dictionary in emacs-25 fails with this error:

    slot-missing: Invalid slot name: "#<helm-source-sync helm-source-sync>", :multimatch

**Comment by thierryvolpiatto** [comment]
Brad Collins <notifications@github.com> writes:

> Calling helm-dictionary in emacs-25 fails with this error:
>
> slot-missing: Invalid slot name: "#<helm-source-sync helm-source-sync>", :multimatch

Not reproductible from 24.5, 25.1 and 26, please check your helm
installation and try to reproduce from a minimal helm configuration,
ideally with emacs-helm.sh.

--
Thierry
