### ISSUE TITLE
thing-at-point as default input

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm-dictionary#30]
I'm not happy with making thing-at-point the default input. It's hardly ever what I want. (I use helm-dictionary mostly while writing, not reading.) I'd like to undo this. But I also want other users to be able to quickly search for the word under the cursor. Two options: we could offer a separate command helm-dictionary-at-point or we could introduce a defcustom that defines whether thing-at-point should be used by default. I prefer the former solution, because I could bind both helm-dictionary functions to keys and use them side-by-side. What do you think, @thierryvolpiatto.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> I'm not happy with making thing-at-point the default input. It's
> hardly ever what I want.

I wonder why I added this (:input) I generally dislike it, it is why I
have implemented :default which is much better and I think it is what
you want, just replace :input by :default and see if it helps.
If one want to have the same behavior as with :input, he can add the
dictionary source to `helm-sources-using-default-as-input`.
You can also let-bound `helm--maybe-use-default-as-input` to an optional
var to have the same effect.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tmalsburg** [comment]
Thanks for the explanation, Thierry.  I changed it following your suggestion.  Always discovering new helm features :)
